apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-games-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-games
  template:
    metadata:
      labels:
        app: card-games
    spec:
      containers:
      - image: cheemcheem/card-games:<TAG>
        name: card-games-container
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 1
          periodSeconds: 10
        env:
        - name: JPA_URL
          valueFrom:
            secretKeyRef:
              name: <SECRET_NAME>
              key: CARD_JPA_URL
        - name: JPA_DB
          valueFrom:
            secretKeyRef:
              name: <SECRET_NAME>
              key: CARD_JPA_DB
        - name: JPA_USERNAME
          valueFrom:
            secretKeyRef:
              name: <SECRET_NAME>
              key: CARD_JPA_USERNAME
        - name: JPA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <SECRET_NAME>
              key: CARD_JPA_PASSWORD
        - name: spring_profiles_active
          value: prod
        - name: SERVER_PORT
          value: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: card-games-service
spec:
  selector:
     app: card-games
  type: ClusterIP
  ports:
    - name: card-games-port
      port: 8080
